### ISSUE TITLE
🐛 [BUG] - date_range_picker() usage in st.form()

### ISSUE THREAD

**Issue by sametsoekel** [arnaudmiribel/streamlit-extras#167]
### Description

Hi,

Works like a charm in the standalone way, but couldn't make it happen in st.form() 

### Reproduction steps

```bash

import streamlit as st
from streamlit_extras.mandatory_date_range import date_range_picker

form = st.form(key="user_form_analysis")

endeks = form.selectbox(
    'Pick a symbol',
    ('A','B','C'))
    
obs_horizon = form.date_range_picker("Select a date range")

get_anaylsis_buton = form.form_submit_button('Get')
```

### Screenshots

![image](https://github.com/arnaudmiribel/streamlit-extras/assets/64185287/09868360-29b6-44d7-ac58-e414f842c0ee)

### Version of streamlit

1.20.0

### Version of streamlit-extras

0.3.0

**Comment by arnaudmiribel** [comment]
Hey @sametsoekel! 

Sorry for the late answer.

To make it work within a form, you should use the `with:` notation instead of calling with the streamlit namespace. Indeed, the `date_range_picker` is not part of the official streamlit namespace.

```python
import streamlit as st 
from streamlit_extras.mandatory_date_range import date_range_picker

form = st.form(key="foo")

form.selectbox("Bar", list("abcd"))
with form:  # <-  see this
    date_range_picker("Select a date range")
form.form_submit_button()
```

But to be fair, the behavior won't be ideal when used in a form, see [demo]([https://playground.streamlit.app?q=form-date-range-picker](https://playground.streamlit.app/?q=form-date-range-picker)):
<img width="609" alt="image" src="https://github.com/arnaudmiribel/streamlit-extras/assets/7164864/2901369d-397a-4ab7-95ec-4e5d7fda8db0">
