### ISSUE TITLE
✨ [Document and Promote CookieManager]

### ISSUE THREAD

**Issue by tonkolviktor** [arnaudmiribel/streamlit-extras#187]
### Description

Cookie manager for Streamlit is an open problem: https://github.com/Mohamed-512/Extra-Streamlit-Components/issues/54
your solution looks good, but it's not easy to find. Maybe promote it better ;)

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by arnaudmiribel** [comment]
Hey @tonkolviktor!

I guess you might be confusing this repo with blipk/StreamlitExtras because we don't have any extra around cookie management in here 😄 But I agree it is quite tricky since three projects share nearly the same name:
- https://github.com/Mohamed-512/Extra-Streamlit-Components
- https://github.com/blipk/StreamlitExtras
- https://github.com/arnaudmiribel/streamlit-extras

Anyway, thanks for sharing!
