### ISSUE TITLE
style_metric_cards bug on dark mode

### ISSUE THREAD

**Issue by 4r7hu3** [arnaudmiribel/streamlit-extras#227]
### Description

*style_metric_cards* does not display values when the dark mode is enabled, hiding the metric, delta and help options from the default *st.metric* method. I tested in three different browsers, with both dark and white mode, and got the same results in all of them: for the white theme, works fine, but has a bug when dark mode is enabled.

![Captura de tela de 2024-04-17 21-37-02](https://github.com/arnaudmiribel/streamlit-extras/assets/83557508/6fde5c9d-67b7-493e-a291-57e583be89f8)

### Reproduction steps

```bash
1. Apply style_metric_cards function to the code
2. create the metrics with st.metric
3. load the page with streamlit run file.py
4. notice the bug
```

### Version of streamlit

streamlit==1.33.0

### Version of streamlit-extras

streamlit-extras==0.4.2

**Comment by arnaudmiribel** [comment]
Hey @4r7hu3! That's a good catch.

It's hard for anyone to contribute new streamlit components that look great both on light and dark or custom themes because streamlit doesn't offer a native way to detect app's theme (you want to upvote the [issue in here](https://github.com/streamlit/streamlit/issues/5009)). That being said, we're lucky and @gabrieltempass just contributed his component to do exactly that into streamlit-extras, see #222. 

![image](https://github.com/arnaudmiribel/streamlit-extras/assets/7164864/506cb1c5-d735-4cd2-8975-4626f0b694e6)

We should come up with different colors for style_metric_cards when in dark mode. Do you have suggestions? You're welcome to hit a PR. I think it should basically just look like that:

```python
from streamlit_extras.theme import st_theme

basis_theme = st_theme["basis"]
if basis_theme == "light":
    # the current code
elif basis_theme == "dark":
    # some new code with other colors
```

Let me know how that sounds! Also cc-ing @dataprofessor who created these custom cards in the first place and might have ideas.

**Comment by arnaudmiribel** [comment]
Closing this issue since there's a proposed fix above.
