### ISSUE TITLE
Website is crashing (just Altex?)

### ISSUE THREAD

**Issue by davidgilbertson** [arnaudmiribel/streamlit-extras#245]
### Description

I go to https://arnaudmiribel.github.io/streamlit-extras/extras/altex/, watch my CPU go to 100% and ~10 seconds later it crashes:
![image](https://github.com/user-attachments/assets/e420d9ba-6f70-4784-b494-282b0d6f6c43)

Tried about 10 times, happens in Arc browser too.

**Comment by arnaudmiribel** [comment]
Hey @davidgilbertson - thank you for spotting that. 

The underlying reason might be that there are a lot of `stlite` playground instances that get started (because Alex has a lot of examples), and since those don't share any resource, they end up overloading and breaking the browser.

A fix to that would be to have a single playground show all of examples. For now I will simply deactivate stlite playgrounds for Altex extra since there's a setting for that (`__stlite__ = False`).

**Comment by davidgilbertson** [comment]
No problems. By the way another page crashed too, sorry I forget which one, somehwere about 10 to 15 down the list on the left.
