### ISSUE TITLE
Not working with the new release of Streamlit 1.14.0

### ISSUE THREAD

**Issue by LorenzoVela** [arnaudmiribel/streamlit-extras#59]
There is a problem with the Rerun function. It has been renamed in the new version and it's raising problems with the **switch_page** functionality (That has not been updated in the new version of streamlit-extras). Is there any plan to fix this issue? Thank you.

**[Workaround for the moment is to downgrade streamlit at 1.13.0 and keep working with that one]**

**Comment by blackary** [comment]
Are you using the latest version of streamlit-extras? 0.2.0 was explicitly updated to support streamlit 1.14.0 -- could you please check if you have 0.2.0 and let me know if it still doesn't work with streamlit 1.14.0?

**Comment by LorenzoVela** [comment]
Yes, I confirm.
From streamlit-extras switch page function are visible these 2 imports

![image](https://user-images.githubusercontent.com/61782614/200674308-6835bdb8-f866-49cc-b144-b06a15d4b425.png)

But in streamlit 1.14.0 __init__ file there is no trace of these function. They've been renamed or replaced:

![image](https://user-images.githubusercontent.com/61782614/200674768-3bdd61d1-d009-40b9-9657-fa81f01c1a1f.png)


This is the error I'm getting:

![image](https://user-images.githubusercontent.com/61782614/200674730-8d4ef2f7-d259-477a-bfd4-15930476ca8b.png)


Don't know if I'm missing something huge but I should've updated everything correctly. Can you may also check? Thank You

**Comment by blackary** [comment]
@LorenzoVela It appears from the stack trace in the error that you're using an old version of streamlit-extras, since it's still trying to import `_RerunData` and `_RerunException` from `streamlit` 
<img width="679" alt="image" src="https://user-images.githubusercontent.com/4040678/200678993-a7a9fb7b-6312-4315-9eec-05df66137bcb.png">

As your first screenshot of the source code of the `switch_page` function shows, these imports have been changed to be imports from `streamlit.runtime.scriptrunner` instead, to be compatible with 1.14.0. 

You can see this live at https://extras.streamlit.app/Switch%20page%20function, which is currently running on streamlit 1.14.0.

Can you please ensure that the version of streamlit-extras that is actually being used in your streamlit app (specifically, whichever version of streamlit-extras is installed in the same conda environment that streamlit is installed in) is 0.2.0?

**Comment by LorenzoVela** [comment]
Hi, I've just downloaded the streamlit-extras package

![image](https://user-images.githubusercontent.com/61782614/200681090-6ac5e460-6245-4b01-ba6b-efe33ba7aaae.png)

And if I try to download streamlit-extras

![image](https://user-images.githubusercontent.com/61782614/200681360-ce38c582-9d1f-4b27-a21a-3170e3765b7f.png)

**Comment by LorenzoVela** [comment]
Checking in your github code the switch page code still try to import RerunData and RerunException so there's something wrong here in github too if you're saying that these are the old imports. Thank You anyway for helping :)

Regards,
Lorenzo

**Comment by arnaudmiribel** [comment]
> Checking in your github code the switch page code still try to import RerunData and RerunException so there's something wrong here in github too if you're saying that these are the old imports.

@LorenzoVela if you look at the main branch of streamlit-extras, the latest release of the switch_page extra does use `RerunData` and `RerunException` which are compatible with streamlit==1.14.0 -- see code [here](https://github.com/arnaudmiribel/streamlit-extras/blob/main/src/streamlit_extras/switch_page_button/__init__.py#L4-L6) after [this commit](https://github.com/arnaudmiribel/streamlit-extras/commit/8bfe14ce224fa00e72fa06390e5dc55689ae6adf) from @blackary. Your screenshot shows an exception being thrown for the usage of `_RerunData` (versus `RerunData`) which clearly shows that it's not using latest versions. 

Would recommend that you make sure to activate your conda environment and upgrade both streamlit and streamlit-extras
```
conda activate && pip install streamlit --upgrade && pip install streamlit-extras --upgrade
```
